# Base configs
baseurl: "https://Parth-Maheshwari.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-146215525-1"

# UI configs
title: "Parth Maheshwari's Photography"
subtitle: "The world is never small. Let's make is more big."
author: "Parth Maheshwari"
header:
 title: "Photography"
 subtitle: "by Parth Maheshwari"
footer:
 name: "Parth"
 bio: "I am Parth. A person with average inclination towards everything and no serious focus. Can discuss ideas to a great length but execute them to no length."
web_design: "AJ"
